fix: errors when no tools match the query
Llama3.1:70b return 'None' and Qwen2.5:32b return '""' when no tools match the query.

This will cause following errors in the log:

Qwen2.5:32b:
...
DEBUG [open_webui.main] content='""'
ERROR [open_webui.main] Error: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/backend/open_webui/main.py", line 445, in chat_completion_tools_handler
    tool_function_name = result.get("name", None)
                         ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
...

Llama3.1:70b:
...
DEBUG [open_webui.main] content='None'
ERROR [open_webui.main] Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/backend/open_webui/main.py", line 443, in chat_completion_tools_handler
    result = json.loads(content)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
...

Signed-off-by: Liu Yuan <namei.unix@gmail.com>