updating bookworm point release to avoid FIPS related build issues
the python:3.11.14-slim-bookworm container has a FIPS related build error:

```
[2/2] STEP 26/42: RUN apt-get update &&     apt-get install -y --no-install-recommends     git build-essential pandoc gcc netcat-openbsd curl jq     libmariadb-dev     python3-dev     ffmpeg libsm6 libxext6 zstd     && rm -rf /var/lib/apt/lists/*
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8792 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [6924 B]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [302 kB]
Fetched 9355 kB in 2s (4172 kB/s)
Reading package lists...fatal error in libgcrypt, file ../../src/misc.c, line 92, function _gcry_fatal_error: requested algo not in md context

Fatal error: requested algo not in md context
Aborted (core dumped)
Error: building at STEP "RUN apt-get update &&     apt-get install -y --no-install-recommends     git build-essential pandoc gcc netcat-openbsd curl jq     libmariadb-dev     python3-dev     ffmpeg libsm6 libxext6 zstd     && rm -rf /var/lib/apt/lists/*": while running runtime: exit status 134
```

This issue is no longer present in the next point release of the container:
python:3.11.15-slim-bookworm