Fix error: error: failed to remove file `/app/.venv/lib/python3.11/site-packages/../../../bin/open-webui`: Permission denied (os error 13) (ALB-164)
This commit follows 29a983f34ebff73e9ced9aa73efbae380c952488

The Pull Request https://github.com/etalab-ia/albert-conversation/pull/98
caused the following bug when starting Docker image albert-conversation/app:

```
error: failed to remove file `/app/.venv/lib/python3.11/site-packages/../../../bin/open-webui`: Permission denied (os error 13)
```

Why? Because the Docker image is executed in production with parameters UID=1001 and GID=1001

This commit changes the owner of /app/* files during image build.

Reference: https://linear.app/albert-conversation/issue/ALB-164/